### ISSUE TITLE
Argument error getting a device/lock by device_id

### ISSUE THREAD

**Issue by byalextran** [seamapi/ruby#166]
in the documentation it shows you can get a device/lock by device_id using `client.locks.get("device-id-here")`, however that throws the following error: 

```
.../locks.rb:13:in `get': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

the only way i could get it to work was with `client.locks.get(device_id: 'device-id-here')`.

**Comment by andrii-balitskyi** [comment]
Hey @byalextran! Sorry for the confusion – all methods now only accept keyword arguments. It seems there are some remnants of the outdated Ruby SDK usage in our docs. Could you point me to the specific documentation with the incorrect sample so we can fix it quickly? Thanks!

**Comment by byalextran** [comment]
here are the two places i saw it in the documentation:

https://docs.seam.co/latest/api/devices/get

https://docs.seam.co/latest/api/locks/get

**Comment by andrii-balitskyi** [comment]
Thank you @byalextran! We'll update those samples shortly.
