### ISSUE TITLE
Migration guide from seamapi Ruby gem

### ISSUE THREAD

**Issue by razor-x** [seamapi/ruby#3]
See for reference seamapi/javascript#1 or seamapi/python#7

**Comment by andrii-balitskyi** [comment]
# Migration guide from seamapi to seam

Learn how to migrate from the `seamapi` package to the `seam` package. This guide includes descriptions of all breaking changes.

The new SDK has fewer dependencies and is generated daily to ensure methods and types are always up-to-date with the latest API changes. It is mostly a drop-in replacement, however some method signatures and options have changed to improve overall consistency with the Seam API.

This guide includes descriptions of all breaking changes. Please refer to the [README](https://github.com/seamapi/ruby/blob/main/README.md) for updated usage instructions and a complete list of new features.

## New Ruby gem name

Changed the gem name from `seamapi` to `seam`.

```diff
- bundle add seamapi
+ bundle add seam
```

## Updated API method signatures

### Keyword arguments

API method signatures now only accept keyword arguments.

```diff
- seam.access_codes.get("my_access_code_id")
+ seam.access_codes.get(access_code_id: "my_access_code_id")
```

```diff
- seam.locks.get("my_lock_device_id")
+ seam.locks.get(device_id: "my_lock_device_id")
```

### Standardized resource ID arguments

Changed from accepting both resource objects and resource ID strings to accepting only resource ID strings. Includes a renaming scheme for clarity.

```diff
- def unlock_door(device_or_id)
+ def unlock_door(device_id:)
```

#### Usage

```diff
- seam.locks.get(device: my_device)
+ seam.locks.get(device_id: my_device.device_id)
```

### Removed methods

Removed `wait_until_finished` from `ActionAttempt` resource. To resolve an action attempt returned by the method, use the `wait_for_action_attempt` method argument instead.

```diff
- seam.locks.unlock_door(device_id: my_device.device_id).wait_until_finished
+ seam.locks.get(device_id: my_device.device_id, wait_for_action_attempt: true)
```

### Deprecated methods

#### `seam.unmanaged_access_codes`

`seam.unmanaged_access_codes` is now deprecated, use `seam.access_codes.unmanaged` instead.

```diff
- seam.unmanaged_access_codes.get(access_code_id: "my_access_code_id")
+ seam.access_codes.unmanaged.get(access_code_id: "my_access_code_id")
```

#### `seam.unmanaged_devices`

`seam.unmanaged_devices` is now deprecated, use `seam.devices.unmanaged` instead.

```diff
- seam.unmanaged_devices.get(device_id: "my_device_id")
+ seam.devices.unmanaged.get(device_id: "my_device_id")
```

## Return value changes

Changed the return values for some methods to enhance API consistency and reliability.

The following methods now return `nil`:

  - `access_codes.delete`: Instead, you should wait for the `access_code.deleted` event.
  - `access_codes.update`: Instead, you should watch for relevant `access_code.*` events or poll the resource as needed.
  - `access_codes.unmanaged.delete`
  - `access_codes.unmanaged.convert_to_managed`: Instead, you should wait for the `access_code.unmanaged.converted_to_managed` and `access_code.unmanaged.failed_to_convert_to_managed` events.

The following methods now return an `ActionAttempt`:

- `workspaces.reset_sandbox`: Instead, you should use the newly-created `action_attempt_id` to poll the status of the action attempt via the `/action_attempt/get` endpoint.

## Action attempt resolution

Methods returning action attempts still wait for the action attempt to resolve by default. Further, you can now configure this behavior using the [`wait_for_action_attempt` option](https://github.com/seamapi/ruby/blob/main/README.rst#action-attempts) on a per-request basis. You can also set the default behavior for the client.

### Set per request

```py
# Wait for the action attempt to be ready with a default timeout of 5.0 seconds and a default polling interval of 0.5 seconds.
seam.locks.lock_door(
    device_id="my_device_id",
    wait_for_action_attempt=True
)

# Wait up to 10 seconds for the action attempt to be ready, checking every 2 seconds.
seam.locks.lock_door(
    device_id="my_device_id",
    wait_for_action_attempt={
        "timeout": 10.0,  # Up to 10 seconds
        "polling_interval": 2.0  # Every 2 seconds
    }
)
```

### Set default behavior

```py
seam = Seam(wait_for_action_attempt=True)
```

## Environment variables

Added support for the `SEAM_ENDPOINT` environment variable.

## Third-party component support and version changes

- Updated the minimum supported Python version to 3.9.
- Updated the `dataclasses-json` version to 0.6.
- Removed Sentry support.
- Replaced `requests` with `niquests` version 3.


## Highlighted new features

### API key authentication with `from_api_key` factory method

Added a new `from_api_key` factory method for API key authentication of the `Seam` client.

```py
seam = Seam.from_api_key("your-api-key")
```

### PAT authentication scoped to a single workspace

Added support for workspace personal access token (PAT) authentication.

```py
# Pass as an option to the constructor
seam = Seam(
    personal_access_token="your-personal-access-token",
    workspace_id="your-workspace-id",
)

# Use the factory method
seam = Seam.from_personal_access_token(
    "your-personal-access-token",
    "your-workspace-id",
)
```

### PAT authentication not bound to a specific workspace

For authentication with a personal access token not bound to a specific workspace, use `SeamMultiWorkspace`.

```py
from seam import SeamMultiWorkspace

# Pass as an option to the constructor
seam_multi_workspace = SeamMultiWorkspace(personal_access_token="your-personal-access-token")

# Use the factory method
seam_multi_workspace = SeamMultiWorkspace.from_personal_access_token("your-personal-access-token")

workspace = seam_multi_workspace.workspaces.create(company_name="Example Inc.")
```

### Webhook handler

SDK exports a thin wrapper `SeamWebhook` around the svix package. Use it to parse and validate Seam webhook events.

**Comment by andrii-balitskyi** [comment]
@razor-x here's the first version of migration guide. Some things are still not implemented, like:
- allow using `Seam.new` and not `Seam::Client.new`
- rename `ClientMultipWorkspace` to `SeamMultiWorkspace` and expose it from the SDK to be used as `SeamMultiWorkspace.new` without the `Seam` namespace
- add `SeamWebhook`

**Comment by razor-x** [comment]
@andrii-balitskyi We don't need to add more top level name, we can keep `Seam::Webhook` and `Seam::Http::MultiWorkspace` (this last one is a more advanced use case anyway). Refer back to this issue for the target structure we worked on https://github.com/seamapi/ruby-next/issues/115

**Comment by andrii-balitskyi** [comment]
@razor-x Yes, that's how we implemented it. The [comment](https://github.com/seamapi/ruby-next/issues/3#issuecomment-2273744641) you're referring to is outdated (from August 7th). I've updated it to avoid confusion.
